[browser]
type = chromium
headless = false
cdp_url = http://localhost:9222

[vfs-credential]
email = calcutta53.mufaddal@gmail.com
password = Mufaddal@9900


; https://visa.vfsglobal.com/are/en/mlt/register
